In [1]:
print("Hello")

Hello

In [3]:
import pandas as pd 
a=[1,7,2]
print(a)
myvar=pd.Series(a)
print("This coloumn, which is converted by series",myvar)

[1, 7, 2]
This coloumn, which is converted by series 0    1
1    7
2    2
dtype: int64

In [19]:
import pandas as pd

calories = {
    "Day1": 20,
    "Day2": 40,
    "Day3": 50
}

print(calories)

{'Day1': 20, 'Day2': 40, 'Day3': 50}

In [20]:
import pandas as pd

data = {
    "calories": [420,380,390],
    "duration": [50,40,45]
}

df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [21]:
#make a data frame into dictionary in pandas

import pandas as pd

data = {
    "Employee_Name": ["Navu", "Indu", "Sandu", "Raju", "Sacchuu","Nitesh","Balen"],
    "Designation": ["Manager", "Developer", "Accountant", "Designer", "HR","Marketing head","Receptionist"],
    "Salary": [50000, 45000, 40000, 42000, 38000,100000,40000]
}


df = pd.DataFrame(data)

print(df)
df.head(7)

  Employee_Name     Designation  Salary
0          Navu         Manager   50000
1          Indu       Developer   45000
2         Sandu      Accountant   40000
3          Raju        Designer   42000
4       Sacchuu              HR   38000
5        Nitesh  Marketing head  100000
6         Balen    Receptionist   40000

  Employee_Name     Designation  Salary
0          Navu         Manager   50000
1          Indu       Developer   45000
2         Sandu      Accountant   40000
3          Raju        Designer   42000
4       Sacchuu              HR   38000
5        Nitesh  Marketing head  100000
6         Balen    Receptionist   40000

In [22]:
df=pd.read_csv("customers-100.csv")
# df=read.excel(file_name.xls)
print(df)
df.head()

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda                   -1199
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka                   -3769
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info         8/24/2020
1         686-620-1820x944                 vmata@colon.com         4/23/2021
2      (496)978-3969x58947             beckycarr@hogan.com         3/25/2020
3                    -9892     stanleyblackwell@benson.org          6/2/2020
4    001-199-446-3860x3486         colinalvarado@miles.net         4/17/2021
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com         1/30/2022
96            605.413.3198               vkemp@ferrell.com         7/10/2021
97   +1-632-666-7507x92121                swagner@kane.org         9/18/2021
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz         8/11/2021
99            783.639.1472          colleen91@faulkner.biz         3/11/2020

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,3/25/2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    str
 2   First Name         100 non-null    str
 3   Last Name          100 non-null    str
 4   Company            100 non-null    str
 5   City               100 non-null    str
 6   Country            100 non-null    str
 7   Phone 1            100 non-null    str
 8   Phone 2            100 non-null    str
 9   Email              100 non-null    str
 10  Subscription Date  100 non-null    str
 11  Website            100 non-null    str
dtypes: int64(1), str(11)
memory usage: 9.5 KB

In [24]:
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [25]:
df = pd.read_csv("Mobile_data.csv")
df.head(15)

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.000,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.000,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.000,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.000,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.000,3000.0,20-Apr
5,5,Honor,10 6/64GB Black,Android,71,10865,10631.0,11099.0,2,5.80,64.000,3400.0,18-Jun
6,6,Honor,10 Lite 3/32GB Blue,Android,424,3999,NaN,NaN,2,6.21,32.000,3400.0,18-Dec
7,7,Honor,10 Lite 4/64GB Black,Android,134,4973,4733.0,5295.0,6,6.21,64.000,3400.0,19-Jan
8,8,Honor,10 lite 3/128GB Blue,Android,477,5100,4990.0,5222.0,3,6.21,128.000,3400.0,21-Jan
9,9,Honor,10 lite 3/64GB Black,Android,215,4948,4646.0,5372.0,8,6.21,64.000,3400.0,18-Dec
10,10,Honor,10 lite 3/64GB Black,Android,179,4948,4646.0,5372.0,8,6.21,64.000,3400.0,18-Dec
11,11,Honor,10 lite 3/64GB Blue,Android,437,5165,4897.0,5559.0,7,6.21,64.000,3400.0,18-Dec
12,12,Nokia,105 DS 2019 Pink (16KIGP01A01),NaN,18,583,528.0,649.0,28,1.77,0.004,800.0,19-Oct
13,13,Nokia,105 Dual Sim 2019 Black (16KIGB01A01),NaN,262,601,539.0,703.0,31,1.77,NaN,800.0,19-Nov
14,14,Nokia,105 Dual Sim 2019 Black (16KIGB01A01),NaN,274,601,539.0,703.0,31,1.77,NaN,800.0,19-Nov

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [27]:
df.describe()

,Unnamed: 0,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size
count,1224.000000,1224.000000,1224.000000,964.000000,964.000000,1224.000000,1222.000000,1112.000000,1214.000000
mean,611.500000,612.500000,7941.206699,7716.018672,9883.410788,16.743464,5.394378,95.700059,3608.201812
std,353.482673,353.482673,8891.836260,8560.959059,11514.936818,20.597006,1.476991,111.922576,1668.268774
min,0.000000,1.000000,214.000000,198.000000,229.000000,1.000000,1.400000,0.003200,460.000000
25%,305.750000,306.750000,2599.750000,2399.000000,2887.000000,2.000000,5.162500,32.000000,2900.000000
50%,611.500000,612.500000,4728.000000,4574.000000,5325.500000,8.000000,6.000000,64.000000,3687.000000
75%,917.250000,918.250000,9323.000000,9262.250000,12673.750000,26.000000,6.400000,128.000000,4400.000000
max,1223.000000,1224.000000,56082.000000,49999.000000,69999.000000,125.000000,8.100000,1000.000000,18800.000000

In [28]:
df.columns

Index(['Unnamed: 0', 'brand_name', 'model_name', 'os', 'popularity',
       'best_price', 'lowest_price', 'highest_price', 'sellers_amount',
       'screen_size', 'memory_size', 'battery_size', 'release_date'],
      dtype='str')

In [29]:
df = df.drop('Unnamed: 0', axis=1)

In [30]:
df.columns

Index(['brand_name', 'model_name', 'os', 'popularity', 'best_price',
       'lowest_price', 'highest_price', 'sellers_amount', 'screen_size',
       'memory_size', 'battery_size', 'release_date'],
      dtype='str')

In [31]:
df.head()

,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [32]:
df["brand_name"].unique()

<StringArray>
[     'ALCATEL',        'Nokia',        'Honor',        'Meizu',
       'realme',      'OnePlus',       'Archos',      'Ulefone',
          'AGM',         'OPPO',        'Astro',       'Rezone',
    'Blackview',       'Bravis',          'NUU',       'Lenovo',
      'UMIDIGI',    'Assistant',    'Crosscall',        'Sharp',
         'ERGO',        'Tecno',          'CAT',       'DOOGEE',
       'Xiaomi',          'ZTE',      'Oukitel',        'Cubot',
       'S-TELL', 'Sigma mobile',      'Coolpad',       'Bluboo',
           'LG',     'Motorola',      'Philips',           '2E',
          'Fly',      'Samsung',    'Prestigio',      'myPhone',
   'BlackBerry',      'KENEKSI',       'Maxcom',       'HUAWEI',
       'Vernee',      'General',       'Globex',      'Smartex',
       'Google',         'ASUS',         'Land',        'MAFAM',
        'Jinga',     'Vodafone',    'Microsoft',     'iOutdoor',
     'Elephone',          'HTC',        'Viaan',         'vivo',
         'Sony',       'LEAGOO',         'Nomi',        'Apple']
Length: 64, dtype: str

In [34]:
df[df["brand_name"] == "vivo"]
df['brand_name'].value_counts()

brand_name
Samsung         168
Xiaomi          111
Apple           102
Motorola         62
Sigma mobile     52
               ...
Land              1
MAFAM             1
Vodafone          1
Microsoft         1
LEAGOO            1
Name: count, Length: 64, dtype: int64